# -*- coding: utf-8 -*-
"""RepVit_Classification_on_ImageNet-1K_reproduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6AnTlSiNAFvkyOLj6OAG92I8TOZ8X81
"""

# 1: Mount
from google.colab import drive
drive.mount('/content/drive')

# 2: GPU 확인
!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# 3: RepViT 코드 클론 & 패키지 설치
!git clone https://github.com/THU-MIG/RepVit.git
# %cd RepVit
!pip install -r requirements.txt

# 4. 압축 해제
!mkdir -p /content/imagenet/val
! tar -xf /content/drive/MyDrive/ILSVRC2012_img_val.tar -C /content/imagenet/val

# 5. 클래스별 폴더 정리
!wget https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh
!mv valprep.sh /content/imagenet/val/
!cd /content/imagenet/val && bash valprep.sh

# 6. 폴더 구조 확인
import os
val_dir = '/content/imagenet/val'
folders = [f for f in os.listdir(val_dir) if os.path.isdir(os.path.join(val_dir, f))]
print(f"클래스 폴더 수: {len(folders)}")  # 1000 이 나와야 정상

# 7. RepVit-M Series Pretrained 모델별 다운로드 (only 300 epochs)
!mkdir pretrain

# M0.9
!wget -P pretrain https://github.com/THU-MIG/RepViT/releases/download/v1.0/repvit_m0_9_distill_300e.pth

# M1.0
!wget -P pretrain https://github.com/THU-MIG/RepViT/releases/download/v1.0/repvit_m1_0_distill_300e.pth

# M1.1
!wget -P pretrain https://github.com/THU-MIG/RepViT/releases/download/v1.0/repvit_m1_1_distill_300e.pth

# M1.5
!wget -P pretrain https://github.com/THU-MIG/RepViT/releases/download/v1.0/repvit_m1_5_distill_300e.pth

# M2.3
!wget -P pretrain https://github.com/THU-MIG/RepViT/releases/download/v1.0/repvit_m2_3_distill_300e.pth

print("모든 모델 다운로드 완료")

from PIL import Image
import os
import subprocess
import re

# dummy 이미지 생성 (추론 전 필수!)
os.makedirs('/content/imagenet/train/dummy', exist_ok=True)
img = Image.new('RGB', (224, 224))
img.save('/content/imagenet/train/dummy/dummy.JPEG')
print("dummy 이미지 생성 완료!")

# 검증할 모델 목록
models = [
    ("repvit_m0_9", "pretrain/repvit_m0_9_distill_300e.pth", 78.7),
    ("repvit_m1_0", "pretrain/repvit_m1_0_distill_300e.pth", 80.0),
    ("repvit_m1_1", "pretrain/repvit_m1_1_distill_300e.pth", 80.7),
    ("repvit_m1_5", "pretrain/repvit_m1_5_distill_300e.pth", 82.3),
    ("repvit_m2_3", "pretrain/repvit_m2_3_distill_300e.pth", 83.3),
]

results = []

for model_name, ckpt_path, paper_acc in models:
    print(f"\n{'='*50}")
    print(f"현재 실행 중: {model_name}")
    print(f"{'='*50}")

    cmd = f"""python main.py \
        --eval \
        --model {model_name} \
        --resume {ckpt_path} \
        --data-path /content/imagenet"""

    output = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    stdout = output.stdout + output.stderr

    # 결과에서 Acc@1 추출
    match = re.search(r'Acc@1\s+([\d.]+)', stdout)
    if match:
        acc1 = float(match.group(1))
        diff = acc1 - paper_acc
        results.append((model_name, paper_acc, acc1, diff))
        print(f"완료! Acc@1: {acc1:.3f}%")
    else:
        print(f"결과 추출 실패")
        print(stdout[-500:])

# 최종 결과 출력
print(f"\n{'='*50}")
print(f"{'모델':<15} {'논문':>8} {'재현':>8} {'차이':>8}")
print(f"{'='*50}")
for model_name, paper_acc, acc1, diff in results:
    print(f"{model_name:<15} {paper_acc:>7.1f}% {acc1:>7.3f}% {diff:>+7.3f}%")
print(f"{'='*50}")